//
// Created by denn on 22.06.2022.
//

#ifndef DEHANCER_GPULIB_HISTOGRAM_COMMON_H
#define DEHANCER_GPULIB_HISTOGRAM_COMMON_H

#define DEHANCER_HISTOGRAM_SIZE 256
#define DEHANCER_HISTOGRAM_CHANNELS 4

#define DEHANCER_HISTOGRAM_BUFF_SIZE (DEHANCER_HISTOGRAM_SIZE+1)
#define DEHANCER_HISTOGRAM_BUFF_LENGTH (DEHANCER_HISTOGRAM_BUFF_SIZE * DEHANCER_HISTOGRAM_CHANNELS)
#define DEHANCER_HISTOGRAM_MULT ((float)(DEHANCER_HISTOGRAM_SIZE))

#endif //DEHANCER_GPULIB_HISTOGRAM_COMMON_H
