//
// Created by denn on 22.06.2022.
//

#ifndef DEHANCER_GPULIB_HISTOGRAM_COMMON_H
#define DEHANCER_GPULIB_HISTOGRAM_COMMON_H

#define DEHANCER_HISTOGRAM_SIZE 256
#define DEHANCER_HISTOGRAM_CHANNELS 4

#define DEHANCER_HISTOGRAM_BUFF_SIZE (DEHANCER_HISTOGRAM_SIZE+1)
#define DEHANCER_HISTOGRAM_BUFF_LENGTH (DEHANCER_HISTOGRAM_BUFF_SIZE * DEHANCER_HISTOGRAM_CHANNELS)
#define DEHANCER_HISTOGRAM_MULT ((float)(DEHANCER_HISTOGRAM_SIZE))

enum DEHANCER_LumaType_t {
    DEHANCER_LUMA_TYPE_YCbCr = 0,
    DEHANCER_LUMA_TYPE_YUV   = 1,
    DEHANCER_LUMA_TYPE_Mean  = 2
};


#endif //DEHANCER_GPULIB_HISTOGRAM_COMMON_H
