//
// Created by denn on 22.06.2022.
//

#ifndef DEHANCER_GPULIB_HISTOGRAM_COMMON_H
#define DEHANCER_GPULIB_HISTOGRAM_COMMON_H

#define DEHANCER_HISTOGRAM_SIZE 256
#define DEHANCER_HISTOGRAM_CHANNELS 4

#endif //DEHANCER_GPULIB_HISTOGRAM_COMMON_H
