//
// Created by dmitry on 14.07.2025.
//

#ifndef DEHANCER_GPULIB_WAVEFORM_COMMON_H
#define DEHANCER_GPULIB_WAVEFORM_COMMON_H

#define DEHANCER_WAVEFORM_SIZE 256
#define DEHANCER_WAVEFORM_CHANNELS 4

#define DEHANCER_WAVEFORM_BUFF_SIZE (DEHANCER_WAVEFORM_SIZE+1)
#define DEHANCER_WAVEFORM_BUFF_LENGTH (DEHANCER_WAVEFORM_BUFF_SIZE * DEHANCER_WAVEFORM_CHANNELS)
#define DEHANCER_WAVEFORM_MULT ((float)(DEHANCER_WAVEFORM_SIZE))

#endif //DEHANCER_GPULIB_WAVEFORM_COMMON_H
